name: config
on: push
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        compiler: [gcc]
    steps:
      - uses: actions/checkout@v2
      - run: echo Stoean Andrei-Cosmin
      - run: gcc -o main src/main.c
      - run: ./main 5 8
      - run: ./main -90 -10
      - run: ./main 100 -100
      - run: ./main 59 81
      - run: ./main -10 6
      - run: |
            if [ "$(./main 4 4)" != "8" ]
              then
                exit 1
            fi 
      - run: |
            if [ "$(./main -15 11)" != "-4" ]
              then
                exit 1
            fi 
      - run: |
            if [ "$(./main -59 -82)" != "-141" ]
              then
                exit 1
            fi 
      - run: |
            if [ "$(./main 100 100)" != "200" ]
              then
                exit 1
            fi 
      - run: |
            if [ "$(./main 5 5)" != "10" ]
              then
                exit 1
            fi